
SimplyAdmire:
  Facets:
    contexts:
      default:
        menu:
          filter: 'SimplyAdmire.Facets:Page'
    defaultReferenceNodePath: /sites/facets/content-elements
    data:
      skeleton: 'resource://SimplyAdmire.Facets/Private/Content/Sites.xml'
      nodeTypes: {  }
      components: {  }
